# Generated by Django 4.2.2 on 2023-06-16 02:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto')),
                ('foto_proyecto_details1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_proyecto_details1')),
                ('foto_proyecto_details2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_proyecto_details2')),
                ('foto_proyecto_details3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_proyecto_details3')),
                ('titulo_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('url_github', models.URLField()),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
